site_name: Sekai Gate Wiki
site_url: https://sekaigate.github.io/SekaiGateWiki/

theme:
  name: material
  language: pl
  features:
    - navigation.sections
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - i18n:
      default_language: pl
      languages:
        - locale: en
          name: English
          build: true
        - locale: pl
          name: Polski
          default: true
          build: true
          nav_translations:
            Home: Strona główna
            Certificates: Certyfikaty
            Regulations: Regulacje
            Penetration Testing: Testy penetracyjne
            Tools: Narzędzia
            Frameworks: Frameworki
            Organizations: Organizacje
nav:
  - Home: index.md
  - Certificates: certificates.md
  - Frameworks: frameworks.md
  - Organizations: organizations.md
  - Regulations:
    - EU AI Act: regulations/eu_ai_act.md
    - ISO: regulations/iso.md
  - Penetration Testing:
    - Tools: penetration_testing/tools.md
  - Large Language Models: 
    - Red Teaming: large_language_model/red_teaming.md
    - Blue Teaming: large_language_model/blue_teaming.md
  - Machine Learning:
    - Red Teaming: machine_learning/red_teaming.md
    - Blue Teaming: machine_learning/blue_teaming.md
  - Natural Language Processing:
    - Red Teaming: natural_language_processing/red_teaming.md
    - Blue Teaming: natural_language_processing/blue_teaming.md
