site_name: Sekai Gate Wiki
site_url: https://sekaigate.github.io/SekaiGateWiki/
repo_url: https://github.com/SekaiGate/SekaiGateWiki
repo_name: SekaiGate/SekaiGateWiki

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - i18n:
      language_detection: true
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: pl
          name: Polski
          build: true
          nav_translations:
            Home: Strona główna
            Certificates: Certyfikaty
            Regulations: Regulacje
            Penetration Testing: Testy penetracyjne
            Tools: Narzędzia
            Frameworks: Frameworki
            Organizations: Organizacje
            Code Analysis: Analiza Kodu
            Training Resources: Materiały szkoleniowe
            Communities: Społeczności
nav:
  - Home: index.md
  - Certificates: certificates.md
  - Frameworks: frameworks.md
  - Organizations: organizations.md
  - Communities: communities.md
  - AI Security Intelligence:
    - AI Incident Database: ai_security_intelligence/ai_incident_database.md
    - Known Exploits & CVEs: ai_security_intelligence/know_exploit_cves.md
  - Regulations:
    - EU AI Act: regulations/eu_ai_act.md
    - ISO: regulations/iso.md
    - AI Assurance Institute: regulations/aiassurance.md
  - Penetration Testing:
    - Tools: penetration_testing/tools.md
  - Code Analysis:
    - Tools: code_analysis/tools.md
  - Model Context Protocol:
    - Training Resources: model_context_protocol/training_resources.md
    - Red Teaming: model_context_protocol/red_teaming.md
    - Blue Teaming: model_context_protocol/blue_teaming.md
  - Large Language Models: 
    - Training Resources: large_language_model/training_resources.md
    - Red Teaming: large_language_model/red_teaming.md
    - Blue Teaming: large_language_model/blue_teaming.md
  - Machine Learning:
    - Red Teaming: machine_learning/red_teaming.md
    - Blue Teaming: machine_learning/blue_teaming.md
  - Natural Language Processing:
    - Red Teaming: natural_language_processing/red_teaming.md
    - Blue Teaming: natural_language_processing/blue_teaming.md
